### ISSUE TITLE
Any chance of adding Tern's contributions to this repo?

### ISSUE THREAD

**Issue by nishakm** [developer-guy/awesome-sbom#2]
I have the following:
- [Nisha Kumar and Allan Friedman - RSAC DevOps connect keynote](https://blogs.vmware.com/opensource/2021/06/15/software-bill-of-materials-and-modern-app-development-devops-connect-rsac-2021/)
- [Rose Judge on using Tern to generate a SBoM for containers](https://blogs.vmware.com/opensource/2020/08/29/rose-judge-on-tern-container-bill-of-materials/)

**Comment by developer-guy** [comment]
Of course @nishak, that would be awesome, please feel free to open PR and I will merge it 🙋🏻‍♂️🙏
